before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Ft6cpeDfBsj1HAoUBq7Wz0r8goKfChTjM3GWkvBxP12K8ZQf5qE6HqBoFNubTIEjDHqBslWr1qsZXMIoEOfX+/9cJw/KqB12ei1vXF26OomlbSHOtL+qnv/IFrft+sBibYffMnicUKAuxgVNDG4leRPcpWY1ODMr8C7r1BYVzG0q7mxEywgsGgKcnrpkqgLD/L4EPKeVYbKC+jvU81IknWcFHEsw3z5MLToEz1kgv032WU37m485OU1g5xfbMYSxKXc2N9nAXomkj+djBfEr+PfEYoAfKc+cWssuJcI10nIh9KwqYXCbxwM/v7xfFjCJ5/yMul0o7l5l2XFnE/lXkYTCA+opZXhINvVJhltZCWEs5Z/8kR7OiMqL4MSf01/1uTaA+5aFp8Kj8M5Q0GnoEpvWK3h38gKw91DUAaIyITgaCcHsKXfjQkjYxVCDcCgb5sTXG7nD85K83OtWAuCGmy6BMksYpg+JR8nk/wtxNGvdS/pCf82rqzDDHSnoJmphZNeB6x4jpc7I4sIMVng8uvm0EXAQPEdI0CuOuTrXjtBLnQmJW3sKdq6b7vPpsswxlbbKQz1kmJuORt0sjopsT7xlqIZ+YOEYqprrafQ3h4wJTTAyjtymyby9AdYqvLGpAgqaNEIpY8AcuITLn2Y7LnY+RX+wa8wk8bzmEMOiQtM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
